apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: samples-logs-back-end-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host:
    http:
      paths:
      - path: /api(/|$)(.*)
        backend:
          serviceName: samples-logs-back-end-svc
          servicePort: 80