apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jovian-outputdata-pvc
spec:
  resources:
    requests:
      storage: 250Gi
  storageClassName: nfs-client
  accessModes:
  - ReadWriteMany