apiVersion: batch/v1
kind: Job
metadata:
  name: jovian-pipeline-installation-job
spec:
  template:
    metadata:
      labels:
        ms: jovian-pipeline-installation-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: main
        image: alexeyebi/jovian-pipeline-installation-job
        volumeMounts:
          - name: body
            mountPath: /git
          - name: data
            mountPath: /mnt/database
      volumes:
        - name: body
          persistentVolumeClaim:
            claimName: jovian-sourcecode-pvc
        - name: data
          persistentVolumeClaim:
            claimName: jovian-databases-pvc
