apiVersion: batch/v1
kind: Job
metadata:
  name: jovian-pipeline-run-job
spec:
  template:
    metadata:
      labels:
        ms: jovian-pipeline-run-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: main
        image: alexeyebi/jovian-pipeline-run-job
        args: ["jovian-pipeline-run-job"]
        resources:
          limits:
            cpu: "19"
            memory: "90Gi"
          requests:
            cpu: "19"
            memory: "90Gi"
        volumeMounts:
          - name: sourcecode
            mountPath: /git
          - name: databases
            mountPath: /mnt/database
          - name: data
            mountPath: /raw_data
          - name: results
            mountPath: /output
      volumes:
        - name: sourcecode
          persistentVolumeClaim:
            claimName: jovian-sourcecode-pvc
        - name: databases
          persistentVolumeClaim:
            claimName: jovian-databases-pvc
        - name: data
          persistentVolumeClaim:
            claimName: jovian-inputdata-pvc
        - name: results
          persistentVolumeClaim:
            claimName: jovian-outputdata-pvc
