apiVersion: v1
kind: Service
metadata:
  name: jovian-sample-status-db-svc
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    ms: jovian-sample-status

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jovian-sample-status-db-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
  accessModes:
  - ReadWriteMany

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jovian-sample-status-db-deployment
spec:
  selector:
    matchLabels:
      ms: jovian-sample-status
  replicas: 1
  template:
    metadata:
      labels:
        ms: jovian-sample-status
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: data
          mountPath: /data/db
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: jovian-sample-status-db-pvc