apiVersion: v1
kind: Service
metadata:
  name: samples-logs-db-svc
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    ms: samples-logs-db

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: samples-logs-db-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
  accessModes:
  - ReadWriteMany

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: samples-logs-db-deployments
spec:
  selector:
    matchLabels:
      ms: samples-logs-db
  replicas: 1
  template:
    metadata:
      labels:
        ms: samples-logs-db
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: data
          mountPath: /data/db
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: samples-logs-db-pvc