apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jovian-databases-pvc
spec:
  resources:
    requests:
      storage: 500Gi
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
