apiVersion: batch/v1
kind: Job
metadata:
  name: ont-pipeline-run-job
spec:
  template:
    metadata:
      labels:
        ms: ont-pipeline-run-job
    spec:
      restartPolicy: Never
      containers:
      - image: alexeyebi/ont-pipeline-run-job
        name: ont-pipeline-run-pod
        args: ["ERR4164785"]
        volumeMounts:
          - name: data
            mountPath: /data
          - name: sourcecode
            mountPath: /git
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: ont-data-pvc
        - name: sourcecode
          persistentVolumeClaim:
            claimName: ont-sourcecode-pvc
