apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jovian-sourcecode-pvc
spec:
  resources:
    requests:
      storage: 250Gi
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
